import re
import glob

Import("root", "runtests")

def do_test(target, source):
	p = root.Program (target, source)
	t = root.Test (target + ".passed", p)
	AlwaysBuild(t)

if runtests:
	for s in glob.glob('test_*.cpp'):
		m = re.match (r"test_(?P<name>.+)\.cpp", s)
		n = m.group ('name')
		if n != '':
			do_test('#bin/unit_tests/' + n, [ s ])
		else:
			print 'Ignoring invalid test file: ' + s
